return {
    EditProfile = "EditProfile", 
    JoinExperience = "JoinExperience", 
    Chat = "Chat", 
    OpenEditProfilePage = "OpenEditProfilePage", 
    Unfriend = "Unfriend", 
    Unblock = "Unblock", 
    AddFriend = "AddFriend", 
    AcceptFriendRequest = "AcceptFriendRequest", 
    PendingFriendRequest = "PendingFriendRequest", 
    CannotAddFriend = "CannotAddFriend", 
    AcceptOffNetworkFriendRequest = "AcceptOffNetworkFriendRequest", 
    ShareProfileQRCode = "ShareProfileQRCode", 
    AddFriendFromContacts = "AddFriendFromContacts", 
    AddFriendFromContactsSent = "AddFriendFromContactsSent"
};
