game:DefineFastString("LuaAppExploreApiSupportedSortNames", "Curated_56,Curated_57,Curated_58,Curated_62,Curated_63,Curated_64,Curated_67,Curated_68,Curated_71,Curated_72,Curated_81,Curated_94,Curated_95,Curated_96,Curated_97,Curated_101,Curated_102,Curated_103,Curated_158,Curated_169,TopRated,TopGrossing,MostEngaging,Popular,PersonalRecommendation,PopularInCountry");
return function()
    return game:GetFastString("LuaAppExploreApiSupportedSortNames");
end;
