return {
    Unknown = "LuaLogout-Unknown", 
    UnauthorizedResponse = "LuaLogout-Unauthorized-Response", 
    UnauthorizedAutoLogin = "LuaLogout-Unauthorized-Auto-Login", 
    AntiAddiction = "LuaLogout-Anti-Addiction", 
    Moderation = "LuaLogout-Moderation", 
    NativeSessionCheck = "LuaLogout-Native-Session-Check", 
    ScreenTimeEvent = "LuaLogout-Screen-Time-Event", 
    MoreLogOut = "LuaLogout-More-Menu-Log-Out", 
    EmailUpsellLogOut = "LuaLogout-Email-Upsell-Log-Out", 
    ContactMethodPrompt = "LuaLogout-Contact-Method-Prompt", 
    QuestU13LogOut = "QuestU13LogOut", 
    PartnerFormNotComplete = "LuaLogout-Partner-Form-Not-Complete", 
    MultiStepSignupCanceled = "LuaLogout-Multi-Step-Signup-Canceled"
};
