return {
    CallBarHangUpClicked = "callBarHangUpClicked", 
    PhoneBookNavigate = "phoneBookNavigate", 
    PhoneBookSearchClicked = "phoneBookSearchClicked", 
    PhoneBookSearchAttempted = "phoneBookSearchAttempted", 
    PhoneBookSearchFinished = "phoneBookSearchFinished", 
    PhoneBookPlayerMenuOpened = "phoneBookPlayerMenuOpened", 
    PhoneBookPlayerMenuUnfriendClicked = "phoneBookPlayerMenuUnfriendClicked", 
    PhoneBookPlayerMenuUnfriendFinished = "phoneBookPlayerMenuUnfriendFinished", 
    PhoneBookPlayerMenuBlockClicked = "phoneBookPlayerMenuBlockClicked", 
    PhoneBookCallFriendClicked = "phoneBookCallFriendClicked", 
    PhoneBookCallFriendFailed = "phoneBookCallFriendFailed"
};
