local l_LocalizedStrings_0 = require(game:GetService("CoreGui"):FindFirstChild("RobloxGui"):FindFirstChild("Modules"):FindFirstChild("Shell"):FindFirstChild("LocalizedStrings"));
return {
    Default = {
        Title = l_LocalizedStrings_0:LocalizedString("AlertOccurredTitle"), 
        Msg = l_LocalizedStrings_0:LocalizedString("DefaultAlertPhrase"), 
        Id = 0
    }, 
    UnlockedUGC = {
        Title = l_LocalizedStrings_0:LocalizedString("UnlockedUGCTitle"), 
        Msg = l_LocalizedStrings_0:LocalizedString("UnlockedUGCPhrase"), 
        Id = 101
    }, 
    LostConnection = {
        Controller = {
            Title = l_LocalizedStrings_0:LocalizedString("ControllerLostConnectionTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ControllerLostConnectionPhrase"), 
            Id = 201
        }, 
        ActiveUser = {
            Title = l_LocalizedStrings_0:LocalizedString("ActiveUserLostConnectionTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ActiveUserLostConnectionPhrase"), 
            Id = 202
        }
    }, 
    PlayMyPlaceMoreGames = {
        Title = l_LocalizedStrings_0:LocalizedString("PlayMyPlaceMoreGamesTitle"), 
        Msg = l_LocalizedStrings_0:LocalizedString("PlayMyPlaceMoreGamesPhrase"), 
        Id = 301
    }, 
    CrossPlatformPlayWelcome = {
        Title = l_LocalizedStrings_0:LocalizedString("CPPWelcomeTitle"), 
        Msg = l_LocalizedStrings_0:LocalizedString("CPPWelcomePhrase"), 
        Id = 401
    }, 
    Reauthentication = {
        [0] = {
            Title = l_LocalizedStrings_0:LocalizedString("AlertOccurredTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthUnknownPhrase"), 
            Id = 1001
        }, 
        [1] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutPhrase"), 
            Id = 1002
        }, 
        [2] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1003
        }, 
        [3] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthInvalidSessionPhrase"), 
            Id = 1004
        }, 
        [4] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthUnlinkTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthUnlinkPhrase"), 
            Id = 1005
        }, 
        [5] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1006
        }, 
        [6] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1007
        }, 
        [7] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1008
        }
    }, 
    SignOut = {
        [0] = {
            Title = l_LocalizedStrings_0:LocalizedString("AlertOccurredTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthUnknownPhrase"), 
            Id = 1001
        }, 
        [1] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutPhrase"), 
            Id = 1002
        }, 
        [2] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthSignedOutTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthInvalidSessionPhrase"), 
            Id = 1003
        }, 
        [3] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthUnlinkTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthUnlinkPhrase"), 
            Id = 1004
        }, 
        [4] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1005
        }, 
        [5] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthRemovedTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthRemovedPhrase"), 
            Id = 1006
        }, 
        [6] = nil, 
        [7] = {
            Title = l_LocalizedStrings_0:LocalizedString("ReauthMaintenanceTitle"), 
            Msg = l_LocalizedStrings_0:LocalizedString("ReauthMaintenancePhrase"), 
            Id = 1007
        }
    }, 
    PlatformLink = {
        Title = l_LocalizedStrings_0:LocalizedString("PlatformLinkInfoTitle"), 
        Msg = l_LocalizedStrings_0:LocalizedString("PlatformLinkInfoMessage"), 
        Id = 1201
    }
};
