return {
    EmptyRequest = 1, 
    TooManyAttempts = 2, 
    InvalidDeliveryMethod = 3, 
    InvalidDeliveryTarget = 4, 
    InvalidEmailAddress = 5, 
    InvalidPhoneNumber = 6, 
    PhoneNumberAlreadyLinked = 8, 
    InvalidChallenge = 9, 
    ChallengeExpired = 10, 
    InvalidCode = 11, 
    InvalidVoucher = 12, 
    VoucherExpired = 13, 
    InvalidBirthdate = 14, 
    InvalidPassword = 15, 
    UserCreationFailed = 16, 
    UsernameGenerationFailed = 17, 
    Captcha = 18
};
