return {
    MAX_MESSAGE_LENGTH = 200, 
    CAMERA_CHANGED_EPSILON = 5, 
    BILLBOARD_OFFSET_EPSILON = 0.5, 
    VOICE_STATE = {
        INACTIVE = "Inactive", 
        TALKING = "Talking", 
        CONNECTING = "Connecting", 
        MUTED = "Muted", 
        LOCAL_MUTED = "LOCAL_MUTED", 
        ERROR = "Error", 
        HIDDEN = "Hidden"
    }, 
    AVATAR_CHAT_UI_SETTINGS = {
        FrameHeight = 30, 
        IconSize = UDim2.fromOffset(24, 24), 
        IconTransparency = 0.1, 
        DoubleIconButtonSize = UDim2.fromOffset(38, 30), 
        SingleIconButtonSize = UDim2.fromOffset(30, 30), 
        SingleIconCornerRadiusOffset = 8, 
        DoubleIconCornerRadiusOffset = 10, 
        DividerSize = UDim2.fromOffset(2, 18), 
        DividerColor = Color3.fromHex("#BDBEBE")
    }
};
